### ISSUE TITLE
app didn't work

### ISSUE THREAD

**Issue by ultrach12** [UmeshRajani/Spring5-MVC-Hibernate5-SpringSecurity5-CRUD#1]
pls friend can you send me your email ?

**Comment by UmeshRajani** [comment]
Hi,

After cloning this repo, have you imported this project as existing maven project?
And make sure you ran the [sql script] (https://github.com/UmeshRajani/Spring5-MVC-Hibernate5-SpringSecurity5-CRUD/blob/master/QuickFixer/quickfixer.sql)

Let me know how it is not working, I'll help you.

**Comment by UmeshRajani** [comment]
Fixed
